// To add a new sticker, find the sticker file ID
// This can be done by sending a sticker to the bot and logging the message object or using a utility bot
// [IMPORTANT]: Don't get offended
const STICKERS = [
  "CAACAgUAAxkBAAIjEmWkDMdaYjUf4T6uEmKZqP3_XVt9AALEAwACGvW5VeOu79-faKRbNAQ",
  "CAACAgUAAxUAAWWkDMfX4fHEJcG-8rQB7GW7fgrhAAKsAQACxUqCEX-1oD1MyKOlNAQ",
  "CAACAgUAAxUAAWWkDMecvxZ2zSfFYRyVR3PYDZv5AALcAAPFSoIREnQdO3H1I6c0BA",
  "CAACAgEAAxUAAWWkDMe2KRHTK70T1_bzhF05VLa9AAKFAQACdvbRRjMtRt6ySdtQNAQ",
  "CAACAgEAAxUAAWWkDMevHuSX1bv5eO2wSQffGyhbAAIKAgACVt_JRsKACrLeA-HnNAQ",
  "CAACAgEAAxkBAAIjEWWkDMdNH59blIPM4VHkEs7-T-nBAAK4AQACk6LJRl5lhi-hVIdMNAQ",
  "CAACAgEAAxkBAAIjEGWkDMf7GJvzwlPi_o_tgZFLRx3MAAJuAQACuNfRRthcVisvOTPVNAQ",
  "CAACAgEAAxkBAAIDG2WkDs1753AJ5CqxUEaKKeKXn_MfAALiAAMJxtFG486SznOuxC40BA",
  "CAACAgEAAxkBAAIjb2Wku0h9ffSH5o3KrG-_G8n3ZX2_AAKaAQACF3HRRqGX8GqX54aMNAQ",
  "CAACAgEAAxkBAAIjdGWku4a5-5D8WqiTrk3flix-f6K_AALXAQAC2-fJRmz1bGhY0X9JNAQ",
  "CAACAgEAAxkBAAIjeWWku5C4aUyWv3yBYvt-pMdLItVgAALfAwACqLbIRvsns46pgYiUNAQ",
  "CAACAgEAAxkBAAIjfmWku7Jdec5Q8H4SLFFl_oq4VbaoAALmDwACWBTJRv3vDkn03B_vNAQ",
  "CAACAgEAAxkBAAIjg2Wku7vOEJEIit0R8iyE9nucMgi3AALkAQACSmLRRgXYcdEaCiaKNAQ",
  "CAACAgEAAxkBAAIjiGWku9bjzu1ZiQABSnc3NZcL1eyZHwACUgEAAq890EaH6BJJGefbNTQE",
  "CAACAgEAAxkBAAIjjWWku-5dQEvKuIdjUMSIyrXgh-C2AAKwAQAC_H3QRsdi-nhAGWSPNAQ",
  "CAACAgUAAxkBAAIjkmWkvC9iQKmt-mpQeQZjcpSf2CnbAALHAAPFSoIR_HnuH9xjO_k0BA",
  "CAACAgEAAxkBAAIkAmWo82ZR8iaexHGcZDq3sNY8UvT9AAJWAQACzMHRRl4YPy05Xs2HNAQ",
  "CAACAgUAAxUAAWWo82rpI38WV0jq6qMAARi8ukCQsQAC5QEAAuG8kQTvnIzSTjMkFjQE",
  "CAACAgUAAxkBAAIkDGWo83NnPOrKvL8aFzpayI_6I1_TAALjAQAC4byRBMnaRVi-I79aNAQ",
  "CAACAgUAAxkBAAIkG2Wo8_GT5h5BvRaBtywQWhpPkIuNAAI7BAACIlhAVVgi-y9wL25NNAQ",
  "CAACAgQAAxUAAWbBus1zt0-TVwMbUwW-GMuL69npAAJBAQACqCEhBq9mxhtt7kuLNQQ",
  "CAACAgEAAxUAAWbBusxvVGb7YdOAlTMByXwHVyE8AAJNAQACf63JRqKC0Oe6Dr3nNQQ",
  "CAACAgEAAxUAAWbBusyMIZeROvzDamPcJdOJfW_rAALmDwACWBTJRv3vDkn03B_vNQQ",
  "CAACAgUAAxUAAWbBusyW0NuhOQ7BzKqgoX_t7UxGAAJCBAAC_AFhVEFmD3JxIQ-TNQQ",
  "CAACAgUAAxUAAWbBusyc-Ry3unufmuS5y7oEffI9AAI_EAAChuNBVgpa4tSyQV8dNQQ",
  "CAACAgUAAxUAAWbBvLnW041UZREYUp_GYlD7jQpHAAKeBgACktpJVFO_74Mi1elVNQQ",
  "CAACAgUAAxkBAAJxlGbBvLsItyXAg2OGko_t2af6rYgMAAIlBQACkolJVOQXgOpOuPz-NQQ",
  "CAACAgUAAxkBAAKF6mjO9cmIwojgkY_02LlDNqBLvMwMAAL_AwACtjFoVvQHjvLKYVDzNgQ",
  "CAACAgUAAxkBAAKF8GjO9f49sYWwcIfb5ddjVbNk0KBZAAKfBAACiY1pVvRiRj5RwbQ-NgQ",
  "CAACAgUAAxkBAAKF9mjO9kH2rRS_8ouHz671OeBl75S-AAI5BAACcFe5V1BsSOwW-w52NgQ",
  "CAACAgUAAxkBAAIKG2jO-feQB-VO20xc2rFXAAFkFXcOcwACZwQAApiaeSjcMhPO15rnVzYE",
  "CAACAgUAAxkBAAIKHmjO-ha3MHIOuDCQCCJVgtSCcO5TAAJtBAACmJp5KFSKcVdFWLmTNgQ",
  "CAACAgUAAxkBAAIKIWjO-p02LRI7-ibG0M_KnvDjG7kuAAKHBAACmJp5KNjrFPH7KGsbNgQ",
  "CAACAgUAAxkBAAIKJWjO-5_uk2ndWlx_g7-cYysKu6OkAAKaBAACwLx4VveyyKz1Do-oNgQ",
];

export const getRandomSticker = (): string => {
  return STICKERS[Math.floor(Math.random() * STICKERS.length)]!;
};
