services:
  ktu-bot-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: ktu-bot-app
    env_file:
      - ../env/dev/bot.env
      - ../env/dev/db.env
      - ../env/dev/redis.env
      - ../env/dev/api.env
      - ../env/dev/llm.env
      - ../env/dev/logging.env
      - ../env/dev/.env
    volumes:
      - ..:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      ktu-bot-postgres:
        condition: service_healthy
        restart: true
      ktu-bot-redis:
        condition: service_healthy
        restart: true
      ktu-bot-db-migrations:
        condition: service_completed_successfully
    networks:
      - ktu-bot-network
    command: ["pnpm", "dev:watch"]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-s",
          "-S",
          "--max-time",
          "5",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ktu-bot-db-migrations:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: ktu-bot-db-migrations
    env_file:
      - ../env/dev/db.env
      - ../env/dev/.env
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      ktu-bot-postgres:
        condition: service_healthy
    networks:
      - ktu-bot-network
    command:
      [
        "sh",
        "-c",
        "echo 'Running DB migrations!\n\n' && pnpm db:migrate && echo '\n\nDB Migrations applied successfully!'",
      ]
    restart: "no"

  announcements-notify-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: announcements-notify-worker
    env_file:
      - ../env/dev/bot.env
      - ../env/dev/db.env
      - ../env/dev/redis.env
      - ../env/dev/api.env
      - ../env/dev/llm.env
      - ../env/dev/announcements-notify-worker.env
      - ../env/dev/broadcasts-worker.env
      - ../env/dev/logging.env
      - ../env/dev/.env
    ports:
      - "3001:3001"
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      ktu-bot-postgres:
        condition: service_healthy
        restart: true
      ktu-bot-redis:
        condition: service_healthy
        restart: true
      ktu-bot-db-migrations:
        condition: service_completed_successfully
    networks:
      - ktu-bot-network
    command: ["pnpm", "workers:announcements-notify-worker-dev"]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-s",
          "-S",
          "--max-time",
          "5",
          "http://localhost:3001/health",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  broadcasts-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: broadcasts-worker
    env_file:
      - ../env/dev/bot.env
      - ../env/dev/db.env
      - ../env/dev/redis.env
      - ../env/dev/api.env
      - ../env/dev/broadcasts-worker.env
      - ../env/dev/llm.env
      - ../env/dev/logging.env
      - ../env/dev/.env
    ports:
      - "3002:3002"
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      ktu-bot-postgres:
        condition: service_healthy
        restart: true
      ktu-bot-redis:
        condition: service_healthy
        restart: true
      ktu-bot-db-migrations:
        condition: service_completed_successfully
    networks:
      - ktu-bot-network
    command: ["pnpm", "workers:broadcasts-worker-dev"]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-s",
          "-S",
          "--max-time",
          "5",
          "http://localhost:3002/health",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  data-sync-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: data-sync-worker
    env_file:
      - ../env/dev/bot.env
      - ../env/dev/db.env
      - ../env/dev/api.env
      - ../env/dev/data-sync-worker.env
      - ../env/dev/llm.env
      - ../env/dev/redis.env
      - ../env/dev/logging.env
      - ../env/dev/.env
    ports:
      - "3003:3003"
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      ktu-bot-postgres:
        condition: service_healthy
        restart: true
      ktu-bot-db-migrations:
        condition: service_completed_successfully
    networks:
      - ktu-bot-network
    command: ["pnpm", "workers:data-sync-worker-dev"]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-s",
          "-S",
          "--max-time",
          "5",
          "http://localhost:3003/health",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  attachment-delivery-worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: attachment-delivery-worker
    env_file:
      - ../env/dev/bot.env
      - ../env/dev/db.env
      - ../env/dev/redis.env
      - ../env/dev/api.env
      - ../env/dev/attachment-delivery-worker.env
      - ../env/dev/logging.env
      - ../env/dev/.env
    ports:
      - "3004:3004"
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      ktu-bot-postgres:
        condition: service_healthy
        restart: true
      ktu-bot-redis:
        condition: service_healthy
        restart: true
      ktu-bot-db-migrations:
        condition: service_completed_successfully
    networks:
      - ktu-bot-network
    command: ["pnpm", "workers:attachment-delivery-worker-dev"]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-s",
          "-S",
          "--max-time",
          "5",
          "http://localhost:3004/health",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s

  bull-board-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: bull-board-service
    env_file:
      - ../env/dev/redis.env
      - ../env/dev/bot.env
      - ../env/dev/llm.env
      - ../env/dev/api.env
      - ../env/dev/db.env
      - ../env/dev/bull-board-service.env
      - ../env/dev/logging.env
      - ../env/dev/broadcasts-worker.env
      - ../env/dev/announcements-notify-worker.env
      - ../env/dev/data-sync-worker.env
      - ../env/dev/attachment-delivery-worker.env
      - ../env/dev/.env
    ports:
      - "3010:3010"
    volumes:
      - ..:/app
      - /app/node_modules
    depends_on:
      ktu-bot-redis:
        condition: service_healthy
        restart: true
    networks:
      - ktu-bot-network
    command: ["pnpm", "services:bull-board-dev"]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-s",
          "-S",
          "--max-time",
          "5",
          "http://localhost:3010/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  ktu-bot-postgres:
    image: postgres:17-alpine
    container_name: ktu-bot-postgres-dev
    env_file:
      - ../env/dev/db.env
    volumes:
      - ktu_bot_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ktu-bot-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ktu_bot_user", "-d", "ktu_bot"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: unless-stopped

  ktu-bot-redis:
    image: redis:7-alpine
    container_name: ktu-bot-redis-dev
    env_file:
      - ../env/dev/redis.env
    ports:
      - "6379:6379"
    networks:
      - ktu-bot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - ktu_bot_redis_data:/data

volumes:
  ktu_bot_postgres_data:
  ktu_bot_redis_data:

networks:
  ktu-bot-network:
    driver: bridge
