export { fetchAnnouncements } from "./fetch-announcements.js";
export { fetchAttachment } from "./fetch-attachment.js";
export { fetchTimetables } from "./fetch-timetables.js";
export { fetchAcademicCalendars } from "./fetch-academic-calendars.js";
export { fetchPrograms } from "./fetch-programs.js";
export { fetchSchemes } from "./fetch-schemes.js";
export { fetchBranches } from "./fetch-branches.js";
export { fetchSyllabus } from "./fetch-syllabus.js";
export { fetchSyllabusAttachment } from "./fetch-syllabus-attachment.js";
